# Generated by Django 5.1.4 on 2025-01-16 16:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название источника')),
                ('description', models.TextField(verbose_name='Описание источника')),
                ('source_link', models.URLField(max_length=160, unique=True, verbose_name='Ссылка на источник')),
                ('period', models.IntegerField(verbose_name='Периодичность парсинга источника. В часах')),
                ('youtube_link', models.BooleanField(default=False, verbose_name='Является ли ютуб-каналом')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
            },
        ),
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок статьи')),
                ('article_content', models.TextField(verbose_name='Содержимое статьи')),
                ('article_image', models.ImageField(blank=True, upload_to='', verbose_name='Image')),
                ('article_link', models.URLField(default='default_link_value', max_length=160, unique=True, verbose_name='Ссылка на статью')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape_content_application.contentsource', verbose_name='Источник статьи')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
