# Generated by Django 5.1.4 on 2025-01-16 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_content_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecontent',
            old_name='title',
            new_name='article_title',
        ),
    ]
