# Generated by Django 5.1.4 on 2025-01-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_content_application', '0002_rename_title_articlecontent_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecontent',
            name='article_image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
