# Generated by Django 5.1.4 on 2025-01-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_content_application', '0004_alter_articlecontent_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecontent',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
